baseURL = "https://adykaaa.github.io/blog"
languageCode = "en-us"
title = "Adam Toth"

[params]
  author = "Adam Toth"
  description = "Thoughts on code, software, and the craft of building things."

[menu]
[[menu.main]]
    name = "Home"
    url = "/blog"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/blog/posts"
    weight = 2
[[menu.main]]
    name = "About"
    url = "/blog/about"
    weight = 3

[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = false
    noClasses = true
  [markup.goldmark.renderer]
    unsafe = true
