baseURL = "https://adykaaa.github.io/blog"
languageCode = "en-us"
title = "Adam Toth"

[params]
  author = "Adam Toth"
  description = "My thoughts on sofware, platform engineering, coding... and everything in general."

[caches]
    [caches.images]
    dir = ':cacheDir/images'
